name: Export PowerBI Report

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar exportação
        run: python export_powerbi.py

      - name: Enviar email
        run: python send_report.py
